location="H&S Arnhem Test"

[layers.stops.bus_stops]
geom_type= "points"
type="lines"
input_file="inputs/lines.json"
processors= [{"name"="name_based_deduplicate", "prefix_ignores"=["asdf"]}]
query = """
[out:json][timeout:60];
relation["type"="route"]["route"~"bus|trolleybus"]["ref"~"^(1|2|3|5|7|21|352)$"](51.9,5.819573,52.2,5.989762);
node(r)(51.9,5.819573,52.2,5.989762);
out(51.9,5.819573,52.2,5.989762);
"""
style.color="ffa82d6f"
style.href="https://maps.google.com/mapfiles/kml/shapes/bus.png"